wallpaper {
    monitor = HDMI-A-1
    path = /home/daniel/wallpapers/homer_on_the_trail.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = /home/daniel/wallpapers/homer_on_the_trail.jpg
    fit_mode = cover
}


splash = off
ipc = off
